/* Copyright © 2026 HornsApp. All rights reserved. */
import { IScreenRender, screenRenderModel } from '../models/render/screen.render.model'
import { ViewRender } from '../models/render/view.render.model'
import { categoryModel, ICategory } from '../models/category.model'
import { cardViewModel } from '../models/render/view.render.model'

export class ScreenGeneratorController {

    public async autoGenerateHomeScreen(appId: string, docVersion: Number): Promise<IScreenRender> {
    const views = await this.buildViews()
    const autoGeneratedKey = "AG_HOME_SCREEN_" + appId.toUpperCase()
    const screenRenderObject = {
        key: "RENDER_SCREEN",
        autoGeneratedKey,
        title: {
            en: `${appId}: AGHS v` + docVersion,
            es: `${appId}: AGHS v` + docVersion
        },
        appId,
        docVersion,
        lastUpdate: new Date(),
        views
    }

    return await screenRenderModel.findOneAndUpdate(
        { appId: appId, autoGeneratedKey: autoGeneratedKey, docVersion: docVersion },
        { $set: screenRenderObject },
        {
            upsert: true,
            new: true,
        }
    )
}

    public async findBy(docVersion: number, appId: string): Promise<IScreenRender | undefined> {
        try {
            const item = await screenRenderModel
                .findOne({
                    docVersion: docVersion,
                    appId: appId,
                }) as IScreenRender

            return item
        } catch (e) {
            return undefined
        }
    }

    private async buildViews(): Promise<ViewRender[]> {
        const categories = await categoryModel
            .find<ICategory>()
            .exec() as ICategory[]
        const upcomingImageCards = this.builUpcomingImageCardViews(categories)
        const upcomingCards = this.buildUpcomingCardViews(categories)
        const infoCards = await this.buildInfoCardViews(20)

        const result: ViewRender[] = []

        // Section: Headers - Unique 
        result.push(this.buildEventRow())
        result.push(this.buildUpcomingColumnView("Upcoming", "Próximos", "calendar"))
        result.push(this.buildAd(50, "FIRST_NEWEST_LIST"))

        // Section: Body - Bucle
        const maxLength = Math.max(upcomingImageCards.length, infoCards.length, upcomingCards.length)
        const adCards = this.buildAdsViews(maxLength)
        const socialCards = this.buildSocialNetworkViews(maxLength)
        for (let i = 0; i < maxLength; i++) {
            if (upcomingImageCards[i]) result.push(upcomingImageCards[i])
            if (socialCards[i]) result.push(socialCards[i])
            if (infoCards[i]) result.push(infoCards[i])
            if (upcomingCards[maxLength - (i + 1)]) result.push(upcomingCards[maxLength - (i + 1)])
            if (adCards[i]) result.push(adCards[i])
        }

        return result
    }

    private buildEventRow(): ViewRender {
        const rowView = {
            key: "ROW_VIEW",
            style: {
                elevation: true
            },
            children: {
                key: "CAROUSEL_CARD_VIEW",
                filter: {
                    events: [
                        "680e68a1fd23ead6b0ca6c8c"
                    ]
                },
                take: 1
            }
        }

        return rowView
    }

    private buildUpcomingColumnView(titleEn: string, titleEs: string, icon?: string | null): ViewRender {
        const columnUpcomingView: ViewRender = {
            key: "COLUMN_VIEW",
            data: {
                title: {
                    en: titleEn,
                    es: titleEs
                },
                icon: icon
            },
            children: {
                key: "UPCOMING_CARD_VIEW",
                take: 4
            },
            navigation: {
                key: "UPCOMING_SCREEN"
            }
        }

        return columnUpcomingView
    }

    private buildSocialNetworkViews(maxLength: number): ViewRender[] {
        const result: ViewRender[] = []

        const tikTokCardView = {
            key: "ICON_CARD_VIEW",
            data: {
                title: {
                    en: "Follow us on TikTok",
                    es: "Síguenos en TikTok"
                },
                subtitle: {
                    en: "Did you know about our TikTok? Follow us and find amazing LIVEs",
                    es: "¿Sabías acerca de nuestro TikTok? Síguenos y encuentra increibles videos y LIVEs"
                },
                icon: "tiktok"
            },
            style: {
                textColor: "#FFFFFF",
                backgroundColor: "#29303e"
            },
            navigation: {
                key: "WEB_VIEW_SCREEN",
                parameters: {
                    param_android_uri: "https://www.tiktok.com/@muvinapp"
                }
            }
        }

        const instagramCardView = {
            key: "ICON_CARD_VIEW",
            data: {
                title: {
                    en: "Follow us on Instagram",
                    es: "Síguenos en Instagram"
                },
                subtitle: {
                    en: "Did you know about our IG? Follow us and keep up posted.",
                    es: "¿Sabías acerca de nuestro Instagram? Síguenos y mantente informado."
                },
                icon: "instagram"
            },
            style: {
                textColor: "#FFFFFF",
                backgroundColor: "#4f5bd5"
            },
            navigation: {
                key: "WEB_VIEW_SCREEN",
                parameters: {
                    param_android_uri: "https://www.instagram.com/muvinapp.pe/"
                }
            }
        }

        const spotifyCardView = {
            key: "ICON_CARD_VIEW",
            data: {
                title: {
                    en: "Follow us on Spotify",
                    es: "Síguenos en Spotify"
                },
                subtitle: {
                    en: "Did you know about our playlists on Spotify? There are a bunch of them waiting for you.",
                    es: "¿Sabías acerca de nuestras playlists en Spotify? Hay muchas esperando por ti."
                },
                icon: "spotify"
            },
            style: {
                textColor: "#FFFFFF",
                backgroundColor: "#1DB954"
            },
            navigation: {
                key: "WEB_VIEW_SCREEN",
                parameters: {
                    param_android_uri: "https://open.spotify.com/user/vhx70zw6rpz3qm8u2fsplhwg1"
                }
            }
        }

        const favoriteCardView = {
            key: "ICON_CARD_VIEW",
            data: {
                title: {
                    en: "Save your favorites",
                    es: "Guarda tus favoritos"
                },
                subtitle: {
                    en: "You can save your favorite concerts now, so you can find them easily later.",
                    es: "Ya puedes guardar tus conciertos favoritos y así encontrarlos más fácil luego."
                },
                icon: "favorite"
            },
            style: {
                textColor: "#FFFFFF",
                backgroundColor: "#F61B83"
            },
            navigation: {
                key: "FAVORITE"
            }
        }

        const facebookCardView = {
            key: "ICON_CARD_VIEW",
            data: {
                title: {
                    en: "Follow us on Facebook",
                    es: "Síguenos en Facebook"
                },
                subtitle: {
                    en: "Did you know about our Facebook? Follow us and keep up posted.",
                    es: "¿Sabías acerca de nuestro Facebook? Síguenos y mantente informado."
                },
                icon: "facebook"
            },
            style: {
                textColor: "#FFFFFF",
                backgroundColor: "#3b5998"
            },
            navigation: {
                key: "WEB_VIEW_SCREEN",
                parameters: {
                    param_android_uri: "https://www.facebook.com/muvinapp.pe"
                }
            }
        }

        const items = [tikTokCardView, instagramCardView, spotifyCardView, favoriteCardView, facebookCardView]
        while (result.length < maxLength) {
            for (let i = 0; i < items.length && result.length < maxLength; i++) {
                result.push(items[i])
            }
        }

        return result
    }

    private buildAdsViews(maxLength: number): ViewRender[] {
        const result: ViewRender[] = []

        const firstAdView = this.buildAd(250, "FIRST_NEWEST_LIST")
        const secondAdView = this.buildAd(250, "SECOND_NEWEST_LIST")

        for (let i = 0; i < maxLength; i++) {
            if (maxLength % 2 === 0) {
                result.push(secondAdView)
            } else {
                result.push(firstAdView)
            }
        }

        return result
    }

    private buildAd(height: number, key: string): ViewRender {
        const adView = {
            key: "AD_VIEW",
            style: {
                height: height
            },
            children: {
                key: key
            }
        }

        return adView
    }

    private async buildInfoCardViews(maxLength: number): Promise<ViewRender[]> {
        const cards = await cardViewModel
            .find()
            .limit(maxLength)
            .exec()

        return cards
    }

    private builUpcomingImageCardViews(categories: ICategory[]): ViewRender[] {
        return categories.map(categories => {
            return {
                key: "COLUMN_VIEW",
                data: {
                    title: {
                        en: categories.description?.en,
                        es: categories.description?.es
                    },
                    subtitle: {
                        en: "#" + categories.name.en,
                        es: "#" + categories.name.es
                    }
                },
                children: {
                    key: "UPCOMING_IMAGE_CARD_VIEW",
                    filter: {
                        categories: [categories._id.toString()]
                    },
                    take: 4
                }
            } as ViewRender
        })
    }

    private buildUpcomingCardViews(categories: ICategory[]): ViewRender[] {
        return categories.map(categories => {
            return this.buildUpcomingColumnView(categories.name.en, categories.name.es, null) as ViewRender
        })
    }
}
