/* Copyright © 2025 HornsApp. All rights reserved. */

import mongoose, { Schema, InferSchemaType } from 'mongoose'
import { ViewRenderScheme } from './view.render.model'
import { LocalizedStringSchema } from '../util/localized.string.model'

export type IScreenRender = InferSchemaType<typeof ScreenRenderScheme>

export const ScreenRenderScheme: Schema = new Schema({
    key: { type: String },
    autoGeneratedKey: { type: String },
    appId: { type: String },
    docVersion: { type: Number },
    lastUpdate: Date,
    title: { type: LocalizedStringSchema },
    views: [{ type: ViewRenderScheme }],
})

export const screenRenderModel = mongoose.model<IScreenRender>('Screen_Render', ScreenRenderScheme)
